name: Docker Image CI

on:
  push:
    branches: [ "cicd/jenkins" ]
  pull_request:
    branches: [ "cicd/jenkins" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag utssaha/tech-huddle:$(date +%s)
        docker images
        docker rmi $(docker images -q)
